### ISSUE TITLE
使用MSSQL时发生错误

### ISSUE THREAD

**Issue by wekingc** [IKende/XBlog#3]
DBHelper 我改为

DBContext.SetConnectionDriver<MSSQL>(DB.DB1);
 DBContext.SetConnectionString(DB.DB1, "server=XX.XX.XX.XX;database=blog;pwd=XXXXX;uid=sa;Workstation ID=blog");

ISetting.cs文件 if ((Option.name == IMG_HOST).Count<Option>() == 0)处出现错误如下：

System.Data.SqlClient.SqlException: 'Incorrect syntax near the keyword 'Option'.'

**Comment by beetlex-io** [comment]
``` csharp
Peanut.DBContext.SetConnectionDriver<Peanut.MSSQL>(Peanut.DB.DB1);
```
也有可能这个Option是mssql的一个关键字……

**Comment by wekingc** [comment]
改为 DBContext.SetConnectionDriver<MSSQL>(DB.DB1);
还是出现同样的错误，并没有解决到问题。
我怀疑是SQLite的语法与MSSQL不一样导致的。
Peanut.FieldInfo 重载的 == 产生的Expression 做SQL操作只适用于SQLite，而在MSSQL中出现错误。例如SQLite的数据库和表名使用如”main“.”blog“，而MSSQL使用如"main".dbo."blog"，有不一致的地方。

**Comment by wekingc** [comment]
我终于知道是什么问题了，因为Top，Key，Sequence，Option等都是MSSQL的保留字符，不能用作表名或字段名。
